# Use the official Elasticsearch image
FROM docker.elastic.co/elasticsearch/elasticsearch:8.4.3

# Set environment variables
ENV discovery.type=single-node
ENV xpack.security.enabled=false

# Expose ports
EXPOSE 9200
EXPOSE 9300
