# fly.toml app configuration file generated for llm-pdf-elastic on 2024-06-20T15:19:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-pdf-elastic'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 9200
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 250

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
